available-slot:
  name: '&a&lAVAILABLE PET SLOT'
  lore:
    - ''
    - '&7Hold a pet in your hand and right-click'
    - '&7to add it to your Faction''s active pet slot.'
    - ''
    - '&f* &2Unlock &apets through /buy!'

guide-item:
  name: '&4&lWhat &care Faction Pets?'
  lore:
    - ''
    - '&7Faction pets are virtual pets that grant'
    - '&7special bonuses to the entire faction'
    - '&7&owhen assigned to an active pet slot.'
    - ''
    - '&f* &cUnlock pets from token shop and crates'

aquatic-pet:
  name: '&3&lAquatic &b&lPet'
  texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWVhNmYxOTY1ZGZlZDk4M2EyOGMzOTA2MmVkYjg1NTAzZTc3Njk4MDMzZTE3YzdmY2VhZjNiZjlhY2I4ODI5YyJ9fX0='
  lore:
    - '&7&oFaction pets are virtual pets that grant'
    - '&7&ospecial bonuses to the entire faction!'
    - ''
    - '&3&lABILITIES &f-'
    - '&f* &b&oGrants the ability to heal in water'
    - ''
    - '&7&oright-click to activate pet.'
    - '&7&oleft-click to remove pet.'

token-pet:
  name: '&6&lFarmer &e&lPet'
  texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjdhM2VkNmE2MjljNWVjYmRhM2JhMDYxOTE1ZTVkMWZmNTg4ZTVhMmVjZGM5Zjg0YmY3MDg4Yjc4NzI2NWEzNSJ9fX0='
  lore:
    - '&7&oFaction pets are virtual pets that grant'
    - '&7&ospecial bonuses to the entire faction!'
    - ''
    - '&6&lABILITIES &f-'
    - '&f* &e&oGenerates tokens passively.'
    - ''
    - '&6Tokens &f➟ &e⛁%amount%'
    - ''
    - '&7&oright-click to activate pet.'
    - '&7&oleft-click to remove pet.'

experience-pet:
  name: '&5&lExperience &d&lPet'
  texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjNjMDUwYWVhZWY1MmE0NTFhZGJhZWIxNDI4ZGZmOGZmNjFiMmEyZGU4Y2M1YTQzOTc5Yjk0MTU0NzQ3ZDhjMiJ9fX0='
  lore:
    - '&7&oFaction pets are virtual pets that grant'
    - '&7&ospecial bonuses to the entire faction!'
    - ''
    - '&5&lABILITIES &f-'
    - '&f* &d&oGenerates experience passively.'
    - ''
    - '&5Experience &f➟ &d%amount%'
    - ''
    - '&7&oright-click to activate pet.'
    - '&7&oleft-click to remove pet.'

money-pet:
  name: '&2&lMoney &a&lPet'
  texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWZkMTA4MzgzZGZhNWIwMmU4NjYzNTYwOTU0MTUyMGU0ZTE1ODk1MmQ2OGMxYzhmOGYyMDBlYzdlODg2NDJkIn19fQ=='
  lore:
    - '&7&oFaction pets are virtual pets that grant'
    - '&7&ospecial bonuses to the entire faction!'
    - ''
    - '&2&lABILITIES &f-'
    - '&f* &a&oGenerates money passively.'
    - ''
    - '&2Money &f➟ &a$%amount%'
    - ''
    - '&7&oright-click to activate pet.'
    - '&7&oleft-click to remove pet.'